title: CLATLAB
logo: /images/clij_logo.png
description: GPU-accelerated image processing in Matlab using CLIJ
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
